---
- hosts: all

  become: false

  tasks:
    - name: Set authorized key took from file
      authorized_key:
        user: vagrant
        state: present
        key: https://pstauffer.github.io/pstauffer.pub